import { createTask } from '@/lib/task-store';
import { addTransaction } from '@/lib/finance-store';
import { addProject, getAllProjects } from '@/lib/freelance-store';
import { TeamCollaborationManager } from '@/lib/team-collaboration';

export type ModuleActionContext = {
  stepId: string;
  module: string;
  action: string;
  merged: Record<string, any>;
  queueNotification: (payload: { stepId: string; action: string; title: string; message: string; dedupKey: string }) => {
    queued: boolean;
    deduped: boolean;
    queueSize: number;
  };
};

type ActionHandler = (ctx: ModuleActionContext) => Promise<Record<string, any>>;

class ModuleActionRegistry {
  private handlers = new Map<string, ActionHandler>();
  private loadedPlugins = false;

  register(module: string, action: string, handler: ActionHandler) {
    this.handlers.set(`${module}.${action}`, handler);
  }

  private tryLoadPlugins() {
    if (this.loadedPlugins) return;
    this.loadedPlugins = true;
    // lightweight hook for future dynamic plugins via global injection
    const anyGlobal = globalThis as any;
    const plugins = anyGlobal.__WORKFLOW_MODULE_PLUGINS__;
    if (Array.isArray(plugins)) {
      for (const p of plugins) {
        if (p?.module && p?.action && typeof p?.handler === 'function') {
          this.register(p.module, p.action, p.handler);
        }
      }
    }
  }

  async execute(ctx: ModuleActionContext): Promise<Record<string, any>> {
    this.tryLoadPlugins();

    const exact = this.handlers.get(`${ctx.module}.${ctx.action}`);
    if (exact) return exact(ctx);

    const wildcard = this.handlers.get(`${ctx.module}.*`);
    if (wildcard) return wildcard(ctx);

    throw new Error(`Unsupported module action: ${ctx.module}.${ctx.action}`);
  }
}

export const moduleActionRegistry = new ModuleActionRegistry();

moduleActionRegistry.register('tasks', 'select_priority_task', async ({ merged }) => {
  const created = await createTask({
    title: `[WF] Priority Task Selection - ${new Date().toLocaleDateString()}`,
    description: `Auto-created by workflow, priority: ${merged.priority || 'highest'}`,
    priority: merged.priority === 'highest' ? 'high' : 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 24 * 3600 * 1000).toISOString(),
    assignedTo: 'Me',
    tags: ['workflow', 'auto', 'priority-selection'],
    source: 'workflow',
  } as any);
  if (!created) throw new Error('Task creation failed');
  return { selectedTaskId: created.id, priority: merged.priority || 'highest' };
});

moduleActionRegistry.register('tasks', 'record_progress', async () => {
  const created = await createTask({
    title: `[WF] Progress Record - ${new Date().toLocaleTimeString()}`,
    description: 'Progress record task auto-generated by workflow',
    priority: 'low',
    status: 'pending',
    dueDate: new Date(Date.now() + 12 * 3600 * 1000).toISOString(),
    assignedTo: 'Me',
    tags: ['workflow', 'progress'],
    source: 'workflow',
  } as any);
  if (!created) throw new Error('Progress task creation failed');
  return { recorded: true, taskId: created.id };
});

moduleActionRegistry.register('tasks', '*', async ({ module, action }) => ({ delegated: true, module, action }));
moduleActionRegistry.register('automation', '*', async ({ action }) => ({ executed: true, automationAction: action }));

moduleActionRegistry.register('reporting', '*', async ({ stepId, action }) => {
  const reportTask = await createTask({
    title: `[WF] Report Generation - ${action}`,
    description: `Workflow report task, source step: ${stepId}`,
    priority: 'medium',
    status: 'pending',
    dueDate: new Date(Date.now() + 6 * 3600 * 1000).toISOString(),
    assignedTo: 'Me',
    tags: ['workflow', 'reporting'],
    source: 'workflow',
  } as any);
  if (!reportTask) throw new Error('Report task creation failed');
  return { reportGenerated: true, reportType: action, title: `Workflow Report - ${stepId}`, reportTaskId: reportTask.id };
});

moduleActionRegistry.register('notification', '*', async ({ stepId, action, merged, queueNotification }) => {
  const title = merged.title || `Workflow notification: ${action}`;
  const message = merged.message || `Step ${stepId} executed`;

  TeamCollaborationManager.sendNotification('kane', {
    title,
    message,
    type: 'info',
    action: { label: 'View Workflows', url: '/workflows' },
  });

  const q = queueNotification({
    stepId,
    action,
    title,
    message,
    dedupKey: `${stepId}|${title}|${message}`,
  });

  return {
    notified: q.queued,
    deduped: q.deduped,
    queued: q.queued,
    queueSize: q.queueSize,
    channel: 'notification-queue',
    notificationType: action,
  };
});

moduleActionRegistry.register('finance', 'collect_weekly_data', async ({ stepId, merged }) => {
  const summary = await addTransaction({
    date: new Date().toISOString().slice(0, 10),
    amount: Number(merged.amount || 0),
    category: 'Workflow Collection',
    description: 'Weekly finance collection record (automated)',
    type: 'income',
    currency: 'PHP',
    status: 'completed',
    tags: ['workflow', 'finance'],
    metadata: { workflow: true, stepId },
  } as any);
  return { collected: true, period: merged.period || 'weekly', transactionId: summary.id };
});
moduleActionRegistry.register('finance', '*', async ({ merged }) => ({ collected: true, period: merged.period || 'weekly', source: 'finance-store' }));

moduleActionRegistry.register('freelance', 'search_projects', async ({ action }) => {
  const all = await getAllProjects();
  return { done: true, freelanceAction: action, candidates: all.length };
});

moduleActionRegistry.register('freelance', 'apply_to_projects', async ({ merged, action }) => {
  const project = await addProject({
    title: `[WF] Auto Follow-up ${new Date().toISOString().slice(0, 10)}`,
    description: 'Freelance project follow-up auto-created by workflow',
    status: 'active',
    source: 'workflow',
    businessSource: 'workflow-automation',
    clientName: merged.clientName || 'Auto Lead',
    budget: Number(merged.budget || 0),
    currency: 'PHP',
    deadline: new Date(Date.now() + 7 * 24 * 3600 * 1000).toISOString(),
    progress: 0,
    category: 'AI Service',
    automationStatus: 'queued',
    notes: 'Auto-generated by workflow',
  } as any);
  return { done: true, freelanceAction: action, projectId: project.id };
});

moduleActionRegistry.register('freelance', '*', async ({ action }) => ({ done: true, freelanceAction: action, candidates: 0 }));
moduleActionRegistry.register('health', '*', async ({ action }) => ({ healthy: true, check: action, timestamp: new Date().toISOString() }));
