'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Progress } from '@/components/ui/progress';
import { Input } from '@/components/ui/input';

// 客户端组件，避免hydration错误
function LastUpdatedTime() {
  const [currentTime, setCurrentTime] = useState('');
  
  useEffect(() => {
    setCurrentTime(new Date().toLocaleString());
  }, []);
  
  return <span>{currentTime || '加载中...'}</span>;
}

// 客户端时间格式化组件
function AlertTime({ timestamp }: { timestamp: string }) {
  const [formattedTime, setFormattedTime] = useState('');
  
  useEffect(() => {
    const date = new Date(timestamp);
    setFormattedTime(date.toLocaleTimeString());
  }, [timestamp]);
  
  return <span>{formattedTime || '加载中...'}</span>;
}

import { 
  Search, 
  Filter, 
  RefreshCw, 
  Plus, 
  Settings, 
  AlertTriangle, 
  CheckCircle, 
  XCircle,
  Wrench,
  Key,
  Cloud,
  Brain,
  Code,
  MessageSquare,
  BarChart3,
  Server,
  Globe,
  Eye,
  ExternalLink,
  MoreVertical,
  ChevronRight,
  Download,
  Upload,
  Trash2,
  Edit,
  Copy,
  Shield,
  Zap,
  Clock,
  Users,
  Tag,
  Hash,
  MapPin,
  Mail,
  Phone,
  Calendar,
  CreditCard,
  Lock,
  Unlock,
  Bell,
  Star,
  Heart,
  ThumbsUp,
  ThumbsDown,
  Flag,
  HelpCircle,
  Info,
  Check,
  X,
  Minus,
  PlusCircle,
  MinusCircle,
  AlertCircle,
  BellRing,
  CheckSquare,
  Square,
  Circle,
  Radio,
  ToggleLeft,
  ToggleRight,
  Sun,
  Moon,
  Monitor,
  Wifi,
  WifiOff,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Signal,
  SignalLow,
  SignalMedium,
  SignalHigh,
  SignalZero,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  Airplay,
  Cast,
  CastConnected,
  Disc,
  HardDrive,
  Database,
  ServerCrash,
  Cpu,
  MemoryStick,
  HardDriveDownload,
  HardDriveUpload,
  Network,
  Router,
  WifiHigh,
  WifiLow,
  GlobeLock,
  KeyRound,
  KeySquare,
  Fingerprint,
  Scan,
  ScanFace,
  ScanLine,
  QrCode,
  Barcode,
  ShieldCheck,
  ShieldAlert,
  ShieldOff,
  ShieldQuestion,
  ShieldX,
  LockKeyhole,
  LockKeyholeOpen,
  UnlockKeyhole,
  Keyhole,
  DoorOpen,
  DoorClosed,
  Home,
  Building,
  Factory,
  Warehouse,
  Store,
  Shop,
  ShoppingCart,
  ShoppingBag,
  Package,
  Box,
  Cube,
  Cuboid,
  Cylinder,
  Cone,
  Pyramid,
  Sphere,
  Torus,
  Octagon,
  Hexagon,
  Pentagon,
  Triangle,
  SquareDashed,
  CircleDashed,
  OctagonAlert,
  HexagonAlert,
  PentagonAlert,
  TriangleAlert,
  SquareAlert,
  CircleAlert,
  OctagonX,
  HexagonX,
  PentagonX,
  TriangleX,
  SquareX,
  CircleX,
  OctagonCheck,
  HexagonCheck,
  PentagonCheck,
  TriangleCheck,
  SquareCheck,
  CircleCheck,
  OctagonMinus,
  HexagonMinus,
  PentagonMinus,
  TriangleMinus,
  SquareMinus,
  CircleMinus,
  OctagonPlus,
  HexagonPlus,
  PentagonPlus,
  TrianglePlus,
  SquarePlus,
  CirclePlus,
  OctagonPause,
  HexagonPause,
  PentagonPause,
  TrianglePause,
  SquarePause,
  CirclePause,
  OctagonPlay,
  HexagonPlay,
  PentagonPlay,
  TrianglePlay,
  SquarePlay,
  CirclePlay,
  OctagonStop,
  HexagonStop,
  PentagonStop,
  TriangleStop,
  SquareStop,
  CircleStop,
  Octagon,
  Hexagon,
  Pentagon,
  Triangle,
  Square as SquareIcon,
  Circle as CircleIcon,
  X as XIcon,
  Check as CheckIcon,
  Minus as MinusIcon,
  Plus as PlusIcon,
  AlertCircle as AlertCircleIcon,
  AlertTriangle as AlertTriangleIcon,
  CheckCircle as CheckCircleIcon,
  XCircle as XCircleIcon,
  Info as InfoIcon,
  HelpCircle as HelpCircleIcon,
  Bell as BellIcon,
  BellRing as BellRingIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  Flag as FlagIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldAlert as ShieldAlertIcon,
  ShieldOff as ShieldOffIcon,
  ShieldQuestion as ShieldQuestionIcon,
  ShieldX as ShieldXIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  KeyRound as KeyRoundIcon,
  KeySquare as KeySquareIcon,
  Fingerprint as FingerprintIcon,
  Scan as ScanIcon,
  ScanFace as ScanFaceIcon,
  ScanLine as ScanLineIcon,
  QrCode as QrCodeIcon,
  Barcode as BarcodeIcon,
  Wifi as WifiIcon,
  WifiOff as WifiOffIcon,
  WifiHigh as WifiHighIcon,
  WifiLow as WifiLowIcon,
  Bluetooth as BluetoothIcon,
  BluetoothConnected as BluetoothConnectedIcon,
  BluetoothOff as BluetoothOffIcon,
  Network as NetworkIcon,
  Server as ServerIcon,
  ServerCrash as ServerCrashIcon,
  Cpu as CpuIcon,
  MemoryStick as MemoryStickIcon,
  HardDrive as HardDriveIcon,
  HardDriveDownload as HardDriveDownloadIcon,
  HardDriveUpload as HardDriveUploadIcon,
  Database as DatabaseIcon,
  Disc as DiscIcon,
  Router as RouterIcon,
  Cloud as CloudIcon,
  Globe as GlobeIcon,
  GlobeLock as GlobeLockIcon,
  MapPin as MapPinIcon,
  Mail as MailIcon,
  Phone as PhoneIcon,
  Calendar as CalendarIcon,
  CreditCard as CreditCardIcon,
  Users as UsersIcon,
  User as UserIcon,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  UserCog,
  UserPen,
  UserSearch,
  UserRound,
  UserRoundCheck,
  UserRoundX,
  UserRoundPlus,
  UserRoundMinus,
  UserRoundCog,
  UserRoundPen,
  UserRoundSearch,
  UsersRound,
  UsersRoundPlus,
  UsersRoundMinus,
  UsersRoundCheck,
  UsersRoundX,
  UsersRoundCog,
  UsersRoundPen,
  UsersRoundSearch,
  Building2,
  Home as HomeIcon,
  Factory as FactoryIcon,
  Warehouse as WarehouseIcon,
  Store as StoreIcon,
  Shop as ShopIcon,
  ShoppingCart as ShoppingCartIcon,
  ShoppingBag as ShoppingBagIcon,
  Package as PackageIcon,
  Box as BoxIcon,
  Cube as CubeIcon,
  Cuboid as CuboidIcon,
  Cylinder as CylinderIcon,
  Cone as ConeIcon,
  Pyramid as PyramidIcon,
  Sphere as SphereIcon,
  Torus as TorusIcon,
  Tag as TagIcon,
  Tags,
  Hash as HashIcon,
  Percent,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  BarChart as BarChartIcon,
  PieChart,
  LineChart,
  AreaChart,
  ScatterChart,
  CandlestickChart,
  Graph,
  Activity,
  Target,
  Award,
  Trophy,
  Medal,
  Crown,
  FlagTriangleLeft,
  FlagTriangleRight,
  Flame,
  Droplet,
  Leaf,
  TreePine,
  TreeDeciduous,
  Mountain,
  Waves,
  CloudRain,
  CloudSnow,
  CloudLightning,
  CloudSun,
  CloudMoon,
  Sun as SunIcon,
  Moon as MoonIcon,
  Star as StarIcon2,
  Planet,
  Satellite,
  Rocket,
  UFO,
  Meteor,
  Comet,
  Telescope,
  Microscope,
  Beaker,
  TestTube,
  TestTubeDiagonal,
  FlaskConical,
  FlaskRound,
  Palette,
  Brush,
  PenTool,
  Highlighter,
  Pencil,
  PencilLine,
  PencilRuler,
  Eraser,
  Paintbrush,
  PaintbrushVertical,
  PaintRoller,
  SprayCan,
  Stamp,
  Scissors,
  ScissorsLineDashed,
  Ruler,
  SquarePen,
  CirclePen,
  TrianglePen,
  HexagonPen,
  OctagonPen,
  PentagonPen,
  SquareDashed as SquareDashedIcon,
  CircleDashed as CircleDashedIcon,
  TriangleDashed,
  HexagonDashed,
  OctagonDashed,
  PentagonDashed,
  Square as SquareIcon2,
  Circle as CircleIcon2,
  Triangle as TriangleIcon,
  Hexagon as HexagonIcon,
  Octagon as OctagonIcon,
  Pentagon as PentagonIcon,
  CheckSquare as CheckSquareIcon,
  Square as SquareIcon3,
  Circle as CircleIcon3,
  Radio as RadioIcon,
  ToggleLeft as ToggleLeftIcon,
  ToggleRight as ToggleRightIcon,
  Sun as SunIcon2,
  Moon as MoonIcon2,
  Monitor as MonitorIcon,
  Battery as BatteryIcon,
  BatteryCharging as BatteryChargingIcon,
  BatteryFull as BatteryFullIcon,
  BatteryLow as BatteryLowIcon,
  BatteryMedium as BatteryMediumIcon,
  Signal as SignalIcon,
  SignalLow as SignalLowIcon,
  SignalMedium as SignalMediumIcon,
  SignalHigh as SignalHighIcon,
  SignalZero as SignalZeroIcon,
  Airplay as AirplayIcon,
  Cast as CastIcon,
  CastConnected as CastConnectedIcon,
  Disc as DiscIcon2,
  HardDrive as HardDriveIcon2,
  Database as DatabaseIcon2,
  ServerCrash as ServerCrashIcon2,
  Cpu as CpuIcon2,
  MemoryStick as MemoryStickIcon2,
  HardDriveDownload as HardDriveDownloadIcon2,
  HardDriveUpload as HardDriveUploadIcon2,
  Network as NetworkIcon2,
  Router as RouterIcon2,
  Wifi as WifiIcon2,
  WifiOff as WifiOffIcon2,
  WifiHigh as WifiHighIcon2,
  WifiLow as WifiLowIcon2,
  Globe as GlobeIcon2,
  GlobeLock as GlobeLockIcon2,
  Key as KeyIcon2,
  KeyRound as KeyRoundIcon2,
  KeySquare as KeySquareIcon2,
  Fingerprint as FingerprintIcon2,
  Scan as ScanIcon2,
  ScanFace as ScanFaceIcon2,
  ScanLine as ScanLineIcon2,
  QrCode as QrCodeIcon2,
  Barcode as BarcodeIcon2,
  Shield as ShieldIcon2,
  ShieldCheck as ShieldCheckIcon2,
  ShieldAlert as ShieldAlertIcon2,
  ShieldOff as ShieldOffIcon2,
  ShieldQuestion as ShieldQuestionIcon2,
  ShieldX as ShieldXIcon2,
  Lock as LockIcon2,
  Unlock as UnlockIcon2,
  LockKeyhole as LockKeyholeIcon,
  LockKeyholeOpen as LockKeyholeOpenIcon,
  UnlockKeyhole as UnlockKeyholeIcon,
  Keyhole as KeyholeIcon,
  DoorOpen as DoorOpenIcon,
  DoorClosed as DoorClosedIcon,
  Home as HomeIcon2,
  Building as BuildingIcon,
  Factory as FactoryIcon2,
  Warehouse as WarehouseIcon2,
  Store as StoreIcon2,
  Shop as ShopIcon2,
  ShoppingCart as ShoppingCartIcon2,
  ShoppingBag as ShoppingBagIcon2,
  Package as PackageIcon2,
  Box as BoxIcon2,
  Cube as CubeIcon2,
  Cuboid as CuboidIcon2,
  Cylinder as CylinderIcon2,
  Cone as ConeIcon2,
  Pyramid as PyramidIcon2,
  Sphere as SphereIcon2,
  Torus as TorusIcon2,
  Octagon as OctagonIcon2,
  Hexagon as HexagonIcon2,
  Pentagon as PentagonIcon2,
  Triangle as TriangleIcon2,
  SquareDashed as SquareDashedIcon2,
  CircleDashed as CircleDashedIcon2,
  OctagonAlert as OctagonAlertIcon,
  HexagonAlert as HexagonAlertIcon,
  PentagonAlert as PentagonAlertIcon,
  TriangleAlert as TriangleAlertIcon,
  SquareAlert as SquareAlertIcon,
  CircleAlert as CircleAlertIcon,
  OctagonX as OctagonXIcon,
  HexagonX as HexagonXIcon,
  PentagonX as PentagonXIcon,
  TriangleX as TriangleXIcon,
  SquareX as SquareXIcon,
  CircleX as CircleXIcon,
  OctagonCheck as OctagonCheckIcon,
  HexagonCheck as HexagonCheckIcon,
  PentagonCheck as PentagonCheckIcon,
  TriangleCheck as TriangleCheckIcon,
  SquareCheck as SquareCheckIcon,
  CircleCheck as CircleCheckIcon,
  OctagonMinus as OctagonMinusIcon,
  HexagonMinus as HexagonMinusIcon,
  PentagonMinus as PentagonMinusIcon,
  TriangleMinus as TriangleMinusIcon,
  SquareMinus as SquareMinusIcon,
  CircleMinus as CircleMinusIcon,
  OctagonPlus as OctagonPlusIcon,
  HexagonPlus as HexagonPlusIcon,
  PentagonPlus as PentagonPlusIcon,
  TrianglePlus as TrianglePlusIcon,
  SquarePlus as SquarePlusIcon,
  CirclePlus as CirclePlusIcon,
  OctagonPause as OctagonPauseIcon,
  HexagonPause as HexagonPauseIcon,
  PentagonPause as PentagonPauseIcon,
  TrianglePause as TrianglePauseIcon,
  SquarePause as SquarePauseIcon,
  CirclePause as CirclePauseIcon,
  OctagonPlay as OctagonPlayIcon,
  HexagonPlay as HexagonPlayIcon,
  PentagonPlay as PentagonPlayIcon,
  TrianglePlay as TrianglePlayIcon,
  SquarePlay as SquarePlayIcon,
  CirclePlay as CirclePlayIcon,
  OctagonStop as OctagonStopIcon,
  HexagonStop as HexagonStopIcon,
  PentagonStop as PentagonStopIcon,
  TriangleStop as TriangleStopIcon,
  SquareStop as SquareStopIcon,
  CircleStop as CircleStopIcon,
  Octagon as OctagonIcon3,
  Hexagon as HexagonIcon3,
  Pentagon as PentagonIcon3,
  Triangle as TriangleIcon3,
  Square as SquareIcon4,
  Circle as CircleIcon4,
  X as XIcon2,
  Check as CheckIcon2,
  Minus as MinusIcon2,
  Plus as PlusIcon2,
  AlertCircle as AlertCircleIcon2,
  AlertTriangle as AlertTriangleIcon2,
  CheckCircle as CheckCircleIcon2,
  XCircle as XCircleIcon2,
  Info as InfoIcon2,
  HelpCircle as HelpCircleIcon2,
  Bell as BellIcon2,
  BellRing as BellRingIcon2,
  Star as StarIcon3,
  Heart as HeartIcon2,
  ThumbsUp as ThumbsUpIcon2,
  ThumbsDown as ThumbsDownIcon2,
  Flag as FlagIcon2,
  Shield as ShieldIcon3,
  ShieldCheck as ShieldCheckIcon3,
  ShieldAlert as ShieldAlertIcon3,
  ShieldOff as ShieldOffIcon3,
  ShieldQuestion as ShieldQuestionIcon3,
  ShieldX as ShieldXIcon3,
  Lock as LockIcon3,
  Unlock as UnlockIcon3,
  Key as KeyIcon3,
  KeyRound as KeyRoundIcon3,
  KeySquare as KeySquareIcon3,
  Fingerprint as FingerprintIcon3,
  Scan as ScanIcon3,
  ScanFace as ScanFaceIcon3,
  ScanLine as ScanLineIcon3,
  QrCode as QrCodeIcon3,
  Barcode as BarcodeIcon3,
  Wifi as WifiIcon3,
  WifiOff as WifiOffIcon3,
  WifiHigh as WifiHighIcon3,
  WifiLow as WifiLowIcon3,
  Bluetooth as BluetoothIcon3,
  BluetoothConnected as BluetoothConnectedIcon3,
  BluetoothOff as BluetoothOffIcon3,
  Network as NetworkIcon3,
  Server as ServerIcon3,
  ServerCrash as ServerCrashIcon3,
  Cpu as CpuIcon3,
  MemoryStick as MemoryStickIcon3,
  HardDrive as HardDriveIcon3,
  HardDriveDownload as HardDriveDownloadIcon3,
  HardDriveUpload as HardDriveUploadIcon3,
  Database as DatabaseIcon3,
  Disc as DiscIcon3,
  Router as RouterIcon3,
  Cloud as CloudIcon2,
  Globe as GlobeIcon3,
  GlobeLock as GlobeLockIcon3,
  MapPin as MapPinIcon2,
  Mail as MailIcon2,
  Phone as PhoneIcon2,
  Calendar as CalendarIcon2,
  CreditCard as CreditCardIcon2,
  Users as UsersIcon2,
  User as UserIcon2,
  UserPlus as UserPlusIcon,
  UserMinus as UserMinusIcon,
  UserCheck as UserCheckIcon,
  UserX as UserXIcon,
  UserCog as UserCogIcon,
  UserPen as UserPenIcon,
  UserSearch as UserSearchIcon,
  UserRound as UserRoundIcon,
  UserRoundCheck as UserRoundCheckIcon,
  UserRoundX as UserRoundXIcon,
  UserRoundPlus as UserRoundPlusIcon,
  UserRoundMinus as UserRoundMinusIcon,
  UserRoundCog as UserRoundCogIcon,
  UserRoundPen as UserRoundPenIcon,
  UserRoundSearch as UserRoundSearchIcon,
  UsersRound as UsersRoundIcon,
  UsersRoundPlus as UsersRoundPlusIcon,
  UsersRoundMinus as UsersRoundMinusIcon,
  UsersRoundCheck as UsersRoundCheckIcon,
  UsersRoundX as UsersRoundXIcon,
  UsersRoundCog as UsersRound